# Numpy 檔案讀寫、Mask method

1.  **numpy array 之檔案讀寫 **
2.  **numpy mask method **
3.  **function**
<hr size="5"/>

## 1. numpy array 之檔案讀寫

* np.savetxt / np.loadtxt
* np.save / np.savez /  np.load


在numpy中有很多處理矩陣(array)資料的方法，而這裡我們主要涵蓋比較常用的一些方式。


首先 我們要使用numpy moudule裡的東西必須要import

In [1]:
import numpy as np

注意 : 以下實之範例都以一個2d-array作為例子。  
而其是一個由0~100填滿之二維陣列，其生成方式如下

In [2]:
arr = np.arange(100).reshape(10,10) #2d - array
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


<hr size="5"/>
### np.savetxt

__1. 語法 :__

>numpy.savetxt(__fname__, __X__, __fmt='%.18e'__, __delimiter=' '__, __newline='\n'__, __header=''__, __footer=''__, __comments='# '__)

__2. 變數 : __	

* fname : 檔案名稱，若附檔名為*__.gz__*，檔案自動會以*__gzip__*的形式儲存。  


* X : 要被儲存之變數名稱    



* fmt : 以自訂的格式儲存檔案  



* delimiter : 分隔符號  



* newline : 隔開新行的符號(在1.5.0.版後開始支援)  



* header : 檔頭文字(在1.7.0.版後開始支援)  



* footer : 檔尾文字(在1.7.0.版後開始支援)  



* comments : 註解文字 預設: ‘# ‘, as expected by e.g. numpy.loadtxt.(在1.7.0.版後開始支援)  



參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html


## <hr size="5"/>
### np.loadtxt

__1. 語法 :__

>numpy.loadtxt(__fname__, __dtype=<type 'float'>__,  __comments='#'__, __delimiter=None__, __converters=None__, __skiprows=0__, __usecols=None__, __unpack=False__, __ndmin=0__)

__2. 變數 : __	

* fname : 檔案名稱、路徑，若附檔名為*__.gz__*或__.bz2_，檔案會自動先解壓縮。  

* dtype : 檔案形式，預設為float。



* comments : 註解。



* delimiter : 分隔符號，預設為空白(whitespace)



* converters : dict, optional



* skiprows : 跳過前面n行



* footer : 檔尾文字(在1.7.0.版後開始支援)  



* usecols : 讀入的行數



* unpack : 結構讀入，If true, x, y, z = loadtxt(...)



* ndmin : 讀入之陣列維度，預設是0,1,or2



__3. 回傳 : __  

* ndarray  

參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html


### Ex. 1

>將上面的arr矩陣用__savetxt__存成*text.txt*，再以__np.loadtxt__讀出，並存入物件*hahaha*,最後將*hahaha*印在螢幕上

In [3]:
np.savetxt('text.txt',arr)

In [4]:
hahaha = np.loadtxt('text.txt')
print(hahaha)

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.]
 [ 70.  71.  72.  73.  74.  75.  76.  77.  78.  79.]
 [ 80.  81.  82.  83.  84.  85.  86.  87.  88.  89.]
 [ 90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]]


## <hr size="5"/>
### np.save

__1. 語法 :__

>numpy.loadtxt(__file__, __arr__, __allow_pickle=True__, __fix_imports=True__)

__2. 變數 : __	

* fname : 儲存檔案名稱，將會把檔案存成一個__.npy__之二進位形式



* allow_pickle : 允許矩陣物件使用python pickles.



* fix_imports : bool, optional



* arr : array_like data



參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html


## <hr size="5"/>
### np.savez

__1. 語法 :__

>numpy.savez(file, *args, **kwds)
儲存多個array在一個__.npz__檔案中

__2. 變數 : __	

	
* file : 讀取檔案之路徑


* args : Arguments, optional



* kwds : Keyword arguments, optional




參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html

## <hr size="5"/>
### np.load

__1. 語法 :__

>numpy.load(__file__, __mmap_mode=None__, __allow_pickle=True__, __fix_imports=True__, __encoding='ASCII'__)

__2. 變數 : __	

	
* file : 讀取檔案之路徑


* mmap_mode : {None, ‘r+’, ‘r’, ‘w+’, ‘c’}, optional


* allow_pickle : bool, optional, Default: True


* fix_imports : bool, optional


* encoding : str, optional, Default: ‘ASCII’



__3. 回傳 : __	

* array, tuple, dict, etc.



參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html#numpy.load


### Ex. 2

>將上面的arr矩陣用__save__存成*data.npy*，再以__np.load__讀出，並存入物件*hahaha2*，最後將*hahaha2*印在螢幕上

In [5]:
np.save('data',arr)

In [6]:
hahaha2 = np.load('./data.npy')
print(hahaha2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


<hr size="5"/>
## 2. mask method (濾掉不需要的值)

* 矩陣與數值比較
* Boolean or “mask” index arrays
* numpy.where method

在大氣中我們比較常用來做"mask"的方法大概就以上三種  
同樣以0~100填滿之2d-array作為範例。
<hr size="5"/>

In [7]:
arr = np.arange(100).reshape(10,10) #2d - array
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### 矩陣與數值比較

* 此處我們以找出數值大於五十的數
* 這個方法回傳的是一個Boolean矩陣

In [8]:
print(arr>50)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


### Boolean or “mask” index arrays

* 此處我們以找出數值大於五十的數
* 這個方法回傳的是所有大於50的數組成之矩陣

In [9]:
print(arr[arr>50])

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


### numpy.where method

* 語法 : np.where(判斷式, 要判斷的矩陣, 被篩掉的數值要填入的東西)

參考資料:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

In [10]:
print(np.where(arr>50,arr,np.nan))

[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.]
 [ 70.  71.  72.  73.  74.  75.  76.  77.  78.  79.]
 [ 80.  81.  82.  83.  84.  85.  86.  87.  88.  89.]
 [ 90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]]


### 同場加映

在numpy.ma中有很多類似的套件，大家可以自己去使用看看，不過效果差不多。


參考網址:  
https://docs.scipy.org/doc/numpy-1.13.0/reference/maskedarray.generic.html

In [11]:
print(np.ma.masked_where(arr<50,arr))

[[-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [12]:
print(np.ma.masked_values(arr<50,arr))

[[True -- True True True True True True True True]
 [True True True True True True True True True True]
 [True True True True True True True True True True]
 [True True True True True True True True True True]
 [True True True True True True True True True True]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


<hr size="5"/>
## 3. Function 

Fuction 是一段結構化、可重複使用的程式碼，有易懂、易讀、好維護的特性。


而Python中有很多__built-in__的functions像是__print()__，而你也可以自己創造一個自己的function，而自己定義的function被稱做__user-defined functions__

### Defining a Function  
#### 規則 ：   
 
* Function block 以 __def__ 做開頭，後面緊跟著Function名稱以及小括弧()

* 任何傳入的變數必須放在小括弧中

* 必須要有 ":"

* 必須要在一個block裡寫完(tab)


*我也看不懂我在寫啥，反正規則如下 : *

### Syntax

In [13]:
def functionname( parameters ):
    "function_docstring"
    function_suite
    return [expression]

### Example

In [14]:
def printhaha():
    print("haha")

In [15]:
printhaha()

haha


### 同場加映class範例 stack
參考連結 : https://zh.wikipedia.org/wiki/%E5%A0%86%E6%A0%88

In [16]:
class Stack(object):
    
    def __init__(self):
        self.items = []
        
    def isEmpty(self):
        return self.items == []
    
    def push(self,item):
        self.items.append(item)
        
    def pop(self):
        return self.items.pop()
    
    def peek(self):
        return self.items[len(self.items)-1]
    
    def size(self):
        return len(self.items)