# Numpy 檔案讀寫、Mask method

1.  **numpy array 之檔案讀寫 **
2.  **numpy mask method **
<hr size="5"/>

## <font color='blue'> 1. numpy array 之檔案讀寫 </font>

* np.savetxt / np.loadtxt
* np.save / np.load
* np.savez / np.loadz

在numpy中有很多處理矩陣(array)資料的方法，而這裡我們主要涵蓋比較常用的一些方式。


首先 我們要使用numpy moudule裡的東西必須要import

In [1]:
import numpy as np

注意 : 以下實之範例都以一個2d-array作為例子。  
而其是一個由0~100滿之二維陣列，其生成方式如下

In [2]:
arr = np.arange(100).reshape(10,10) #2d - array
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


<hr size="5"/>
### <font color='blue'> np.savetxt </font>

__1. 語法 :__

>numpy.savetxt(__fname__, __X__, __fmt='%.18e'__, __delimiter=' '__, __newline='\n'__, __header=''__, __footer=''__, __comments='# '__)

__2. 變數 : __	

* fname : 檔案名稱，若附檔名為*__.gz__*，檔案自動會以*__gzip__*的形式儲存。  


* X : 要被儲存之變數名稱    



* fmt : 以自訂的格式儲存檔案  



* delimiter : 分隔符號  



* newline : 隔開新行的符號(在1.5.0.版後開始支援)  



* header : 檔頭文字(在1.7.0.版後開始支援)  



* footer : 檔尾文字(在1.7.0.版後開始支援)  



* comments : 註解文字 預設: ‘# ‘, as expected by e.g. numpy.loadtxt.(在1.7.0.版後開始支援)  



參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html


## <hr size="5"/>
### <font color='blue'> np.loadtxt </font>

__1. 語法 :__

>numpy.loadtxt(__fname__, __dtype=<type 'float'>__,  __comments='#'__, __delimiter=None__, __converters=None__, __skiprows=0__, __usecols=None__, __unpack=False__, __ndmin=0__)

__2. 變數 : __	

* fname : 檔案名稱、路徑，若附檔名為*__.gz__*或__.bz2_，檔案會自動先解壓縮。  

* dtype : 檔案形式，預設為float。



* comments : 註解。



* delimiter : 分隔符號，預設為空白(whitespace)



* converters : dict, optional



* skiprows : 跳過前面n行



* footer : 檔尾文字(在1.7.0.版後開始支援)  



* usecols : 讀入的行數



* unpack : 結構讀入，If true, x, y, z = loadtxt(...)



* ndmin : 讀入之陣列維度，預設是0,1,or2



__3. 回傳 : __  

* ndarray  

參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html


### <font color='red'> Ex. 1 </font>

>將上面的arr矩陣用__savetxt__存成*text.txt*，再以__np.loadtxt__讀出，並存入物件*hahaha*,最後將*hahaha*印在螢幕上

In [3]:
np.savetxt('text.txt',arr)

In [5]:
hahaha = np.loadtxt('text.txt')
print(hahaha)

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.]
 [ 70.  71.  72.  73.  74.  75.  76.  77.  78.  79.]
 [ 80.  81.  82.  83.  84.  85.  86.  87.  88.  89.]
 [ 90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]]


## <hr size="8"/>
### <font color='blue'> np.save </font>

__1. 語法 :__

>numpy.loadtxt(__file__, __arr__, __allow_pickle=True__, __fix_imports=True__)

__2. 變數 : __	

* fname : 儲存檔案名稱，將會把檔案存成一個__.npy__之二進位形式



* allow_pickle : 允許矩陣物件使用python pickles.



* fix_imports : bool, optional



* arr : array_like data



參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html


## <hr size="5"/>
### <font color='blue'> np.load </font>

__1. 語法 :__

>numpy.loadtxt(__file__, __mmap_mode=None__, __allow_pickle=True__, __fix_imports=True__, __encoding='ASCII'__)

__2. 變數 : __	

	
* file : 讀取檔案之路徑


* mmap_mode : {None, ‘r+’, ‘r’, ‘w+’, ‘c’}, optional


* allow_pickle : bool, optional, Default: True


* fix_imports : bool, optional


* encoding : str, optional, Default: ‘ASCII’



__3. 回傳 : __	

* array, tuple, dict, etc.



參考連結 : https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html#numpy.load


### <font color='red'> Ex. 2 </font>

>將上面的arr矩陣用__save__存成*data.npy*，再以__np.load__讀出，並存入物件*hahaha2*，最後將*hahaha2*印在螢幕上

In [6]:
np.save('data',arr)

In [7]:
ls #注意自動會變成.npy檔，並且可以與上面儲存之txt檔比較，占用之空間比較小

 Volume in drive C is OS_Install
 Volume Serial Number is 54A1-CE7C

 Directory of C:\Users\ericakcc\Desktop\work\2017_python_class\Python

2017/09/06  ?? 01:52    <DIR>          .
2017/09/06  ?? 01:52    <DIR>          ..
2017/09/04  ?? 01:18    <DIR>          .ipynb_checkpoints
2017/09/06  ?? 01:52               480 data.npy
2017/09/02  ?? 05:42                47 foo.txt
2017/09/02  ?? 05:28            87,257 Jupyter Notebook Users Manual.ipynb
2017/09/06  ?? 01:51            16,648 mask??.ipynb
2017/09/03  ?? 11:22             9,045 python_IO.ipynb
2017/09/06  ?? 01:35             2,500 text.txt
               6 File(s)        115,977 bytes
               3 Dir(s)  45,352,083,456 bytes free


In [8]:
hahaha2 = np.load('./data.npy')
print(hahaha2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [5]:
arr>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [12]:
arr[arr>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.where(arr>50,arr,np.nan)

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.],
       [ 70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.],
       [ 90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.]])

In [19]:
np.ma.masked_where(arr<50,arr)

masked_array(data =
 [[-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [-- -- -- -- -- -- -- -- -- --]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]],
             mask =
 [[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False Fal

In [20]:
np.ma.masked_values(arr<=50,arr)

masked_array(data =
 [[True -- True True True True True True True True]
 [True True True True True True True True True True]
 [True True True True True True True True True True]
 [True True True True True True True True True True]
 [True True True True True True True True True True]
 [True False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]],
             mask =
 [[False  True False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 